### ISSUE TITLE
Using this with Diablo II

### ISSUE THREAD

**Issue by ross-weir** [MOZGIII/pvpgn-docker#1]
Hi. This might be a long shot and you probably haven't touched this in a while but meh. 👍 

Did you ever get Diablo II working with this docker image? I'm trying to run it on a AWS EC2 instance but no matter what I do I just cannot get my client to connect. 

It seems to be connectivity/port issues. I can ping the instance and I believe I have the AWS security configurations setup properly.

The required ports seem to be getting exposed in the Dockerfile. Do you remember if you ever had to change any pvpgn configuration settings?

Thanks!

**Comment by ross-weir** [comment]
Figured it out. It was a issue with docker networking and my config, trying to run d2gs on Ubuntu also over complicated setup.

**Comment by MOZGIII** [comment]
I'd advice using `--net=host`. It doesn't have an overhead of the usual docker overlay networking.
